local dap = require("dap")
-- dap.adapters.python = {
--   type = 'executable';
--   command = '/home/david/.pyenv/shims/python';
--   args = { '-m', 'debugpy.adapter' };
-- }
-- dap.configurations.python = {
--   {
--     type = 'python';
--     request = 'launch';
--     name = "Launch file";
-- 	}
-- }
